### ISSUE TITLE
proto-pcb improvements:

### ISSUE THREAD

**Issue by cyberboy666** [langolierz/_transcribe_#1]
- the din-midi sockets from tayda are larger than the footprint implied -> looks like they wont currently fit without removing some of the plastic first
-the dsub sockets from tayda dont fit the footprint - holes are too small , and also spacing seems a little different ...
- capicitor footprint is a little too tight, and too close if the dsub did fit
- ~~wrong way footprint for u6 -> flat part should be facing the hostshield (this footprint is a lil small too)~~ , ~~actually looks like the datasheet is. wrong~~
- it is not obvious which way the euro header should go !
- no diodes to protect if usb (arduino and euro powered together)

**Comment by cyberboy666** [comment]
- also should change so both plains are ground and run a trace for +5 ...

**Comment by langolierz** [comment]
looks like the midi out buffers are backwards ?

**Comment by cyberboy666** [comment]
all these things are fixed now, will wait a little while for any more feedback before ordering v0.2

**Comment by cyberboy666** [comment]
want to also at breakout pins for spi/rst to the micro so it can be reflashed more easily while soldered to the board

**Comment by cyberboy666** [comment]
updated to include bootloader breakout
